# Generated by Django 4.2 on 2023-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destiny', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('back_date', models.DateField()),
                ('search_date', models.DateField()),
                ('infos', models.TextField(blank=True, max_length=200)),
                ('class_type', models.CharField(choices=[('ECON', 'Econômica'), ('EXEC', 'Executiva'), ('PRIC', 'Primeira Classe')], default=0, max_length=4)),
            ],
        ),
    ]
